
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

FROM langchain/langchain:0.1.0

RUN apt-get update -y && apt-get install -y --no-install-recommends --fix-missing \
    libgl1-mesa-glx \
    libjemalloc-dev \
    vim

RUN apt-get update  -y \
    && apt-get install -y git wget vim numactl gcc-12 g++-12 python3 python3-pip libtcmalloc-minimal4 \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 10 --slave /usr/bin/g++ g++ /usr/bin/g++-12

RUN echo 'export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4:$LD_PRELOAD' >> ~/.bashrc

RUN useradd -m -s /bin/bash user && \
    mkdir -p /home/user && \
    chown -R user /home/user/

COPY comps /home/user/comps

WORKDIR /home/user/

RUN git clone https://github.com/zhuhaozhe/vllm/ -b debug-ipex
WORKDIR /home/user/vllm
RUN pip install --no-cache-dir --upgrade pip
RUN pip install wheel packaging ninja setuptools numpy
RUN pip install -v -r requirements-cpu.txt --extra-index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /home/user/comps/llms/text-generation/vllm/requirements.txt

RUN pip install http://mlpc.intel.com/downloads/cpu/ipex-2.3.100/rc0_vllm_0528/intel_extension_for_pytorch-2.3.0+gitac44227-cp311-cp311-linux_x86_64.whl
RUN VLLM_TARGET_DEVICE=cpu python setup.py install

ENV PYTHONPATH=$PYTHONPATH:/home/user

USER user
WORKDIR /home/user/comps/llms/text-generation/vllm

ENTRYPOINT ["python", "vllm_openai.py"]
